### PR TITLE
Add customization of HTTP client configuration (#10).

### PR DESCRIPTION
**Pull request by msimonides**

### CODE REVIEW

**Comment by mr3y-the-programmer** [comment]
Thank you for your effort. I'll review this as soon as I get some free time in the next few days. feel free to make any other modifications if you find any thing to improve

**Review by mr3y-the-programmer — CHANGES_REQUESTED** [review]
Hi @msimonides. I reviewed your changes, here are my notes:

1. Revert changes to `CHANGELOG.md` & `README`, I'll update those as soon as I release a new version after merging your changes and I'll give you the credit for it.
2. I discovered that we can apply your proposed changes but also without sacrificing the type safety as you mentioned in the [issue description](https://github.com/mr3y-the-programmer/PodcastIndex-SDK/issues/10#issue-2649073786), here is a pseudocode for the solution:

- Update PodcastIndexClientConfig to have a new function that accepts typed `HttpClientEngineFactory`
```kotlin
internal var httpClientBuilder: (() -> HttpClient)? = null

/**
   * Creates an custom [HttpClient] with the specified [HttpClientEngineFactory] and optional [block] configuration.
   *
   * Note that [block] configuration doesn't replace the existing default configuration added by this library. it will be applied on top of it.
*/
public fun <T : HttpClientEngineConfig> httpClient(
    engineFactory: HttpClientEngineFactory<T>,
    block: HttpClientConfig<T>.() -> Unit = {}
) {
    httpClientBuilder = {
        HttpClient(engineFactory, block)
     }
}
```
- then update `PodcastIndexClient` in base module:
```diff
public class PodcastIndexClient
@InternalPodcastIndexApi
constructor(
-    private val httpClientConfig: HttpClientConfig<*>.() -> Unit,
+    private val defaultHttpClientConfig: HttpClientConfig<*>.() -> Unit,
+    private val podcastIndexClientConfig: PodcastIndexClientConfig
) {

-    private val client: HttpClient = HttpClient(defaultHttpClientEngineFactory()) {
-       httpClientConfig()
+    private val client: HttpClient = podcastIndexClientConfig.httpClientBuilder?.invoke()?.config(defaultHttpClientConfig) ?: HttpClient(defaultHttpClientEngineFactory()) {
+        defaultHttpClientConfig()
    }

```
- Update usages in ktor2 & ktor3 `PodcastIndexClient` accordingly.

The end user can then call & configure the client like this:
```kotlin
val client = PodcastIndexClient(
        API_KEY,
        API_SECRET,
        uAgentString,
    ) {
        enableLogging = true
        maxRetries = 4
        httpClient(OkHttp) {
            // Okhttp specific configuration without any explicit casting
        }
    }
```
Which is idiomatic, type-safe, and doesn't break any existing public API 🚀 

Once you do these changes, we can approve & merge the changes ⭐

**Comment by msimonides** [comment]
Ah, so basically approach no.2 but there's no need to pass the configuration through - it can be applied later.

I made the `httpClientBuilder` non-nullable, it's initialized to build the default `HttpClient`

**Review by mr3y-the-programmer — APPROVED** [review]

**Comment by mr3y-the-programmer** [comment]
Thanks for your contribution, I'll make a release with this new feature.

**Pull request merged**
